name: CI

on: 
  push: 
    branches: [master]
#   workflow_call:
#     inputs:
#       environment:
#         required: true
#         type: string 
#     secrets: 
#       SONAR: 
#         required: true        

  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
#       - run: echo ${{ inputs.environment }}  
      - name: check
        id: mongo
        run: exit 1
      - name: test
        if: ${{ failure() }}
        run: echo 'test'
  check:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo 'test'
   
 
          
