name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          with open('test.json', 'r') as f:
          data = json.load(f)

          # 添加新字段
          data['new_field'] = "example"

          # 将 Python 对象序列化为 JSON 格式的字符串
          new_json = json.dumps(data)

          # 将新的 JSON 字符串写入文件
          with open('test.json', 'w') as f:
            f.write(new_json)

          # 运行结果输出到控制台
          print("Updated JSON content:", new_json)
