name: CI

on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.environment }}  
   
 
          
