name: CI

on: 
  push: 
    branches: [master]
#   workflow_call:
#     inputs:
#       environment:
#         required: true
#         type: string 
#     secrets: 
#       SONAR: 
#         required: true        
env:
  scripts: mongo-scripts
  

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.mongo.outputs.aa }}
    env:
      test: dev
    steps:
      - uses: actions/checkout@v3
        with:
          repository: vickytestcicd/mongo
          path: ${{ env.scripts }}
      - uses: actions/checkout@v3
        with:
          path: "source"
      - run: |
          cd mongo-scripts
          ls
#          sh scripts/mongo/migrate-check.sh
#       - name: check
#         id: mongo
#         run: echo "::set-output name=aa::vlaue"
#       - run: exit 1
#       - name: test
#         if: ${{ failure() }}
#         run: echo ${{ steps.mongo.outputs.aa }}

#   check:
#     runs-on: ubuntu-latest
#     needs: [test]
#     steps:
#       - run: echo 'test'
   
 
          
