name: CI

on:
  push:
#   workflow_call:
#     outputs:
#       deployResulta:
#         description: "the result of deployment"
#         value: ${{ jobs.test.outputs.result }}
#       deployResultb:
#         description: "the result of deployment"
#         value: ${{ jobs.test1.outputs.result }}

jobs:
  testa:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          exit 1
  test:
    runs-on: ubuntu-latest
    needs: [testa]
    if: ${{ always() }}
    outputs:
      bb: ${{ steps.test.outputs.bb }}
      aa: ${{ steps.test.outputs.aa }}
    steps:
      - name: test
        id: test
        run: |
          bb=true
          echo "::set-output name=bb::$bb"
          aa=false
          echo "::set-output name=aa::$aa"

  test2:
    runs-on: ubuntu-latest
    needs: [testa,test]
    if: ${{ always() && (needs.test.outputs.aa==true || needs.test.outputs.bb==true) }}
    steps:
      - name: test
        id: test
        run: |
          echo ${{ needs.test.result }}
          echo ${{ needs.test1.result }}
