name: CI

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          echo "test"
  test2:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: exit 1
  test3:
    runs-on: ubuntu-latest
    needs: [test2]
    steps:
      - run: echo "test3"
  test4:
    runs-on: ubuntu-latest
    needs: [test2,test3]
    if: ${{ always() && needs.test3.result != 'failure' }}
    steps:
      - run: echo "test3"
    
          

#   test2:
#     needs: [test]
#     uses: vickytestcicd/mongo/.github/workflows/main.yml@main
#     with:
#       aa: ${{ needs.test.outputs.aa }}
#       bb: ${{ needs.test.outputs.bb }}
#     if: ${{ always() && ( needs.test.outputs.aa == 'true' || needs.test.outputs.bb == 'true' ) }}
#     needs: [test]
#     if: ${{ needs.test.outputs.aa == 'true' || needs.test.outputs.bb == 'true' }}

          
          
