name: CI

on: 
  push:
    branches: [main]
  

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: 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
    steps:
      - run: | 
          gh api -H "Accept: application/vnd.github+json"  /repos/vickytestcicd/testcicd/branches/main/protection
      - run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token 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" https://api.github.com/repos/vickytestcicd/testcicd/branches/main/protection
          
