name: CI

on: 
  push:
    branches: [main]
  

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      test: a  ab 12  3a
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step1.outputs.test2 }}
    steps:
      - uses: actions/checkout@v3
#       - run: |
#           for i in ${test[*]};do echo $i;done
      - id: step1
        run: | 
          vicky=($(cat test.txt))
           for i in ${vicky[*]} ;do echo $i;done

#       - run: |
#           echo ${${{ steps.step1.outputs.test }}[*]}
#           echo ${{ steps.step1.outputs.test[*] }}
#           echo ${${{ steps.step1.outputs.test2 }}[*]}
#           echo ${{ steps.step1.outputs.test2[*] }}
#       - run: for i in $(cat test.txt);do echo $i;done
          
          
