name: CI

on: 
  push:
    branches: [main]
  

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      test: a  ab 12  3a
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          for i in ${test[*]};do echo $i;done
      - id: step1
        run: | 
          echo "::set-output name=test::($(cat test.txt))"
      - run: |
          for i in ${${{ steps.step1.outputs.test }}[*]};do echo $i;done
          echo ${${{ steps.step1.outputs.test }}[*]}
          echo ${{ steps.step1.outputs.test[*] }}
      - run: for i in $(cat test.txt);do echo $i;done
          
          
