name: CI

on: 
  push:
    branches: [main]
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: | 
          echo ${{ github.api_url }}
          echo ${{ github.repository }}
          echo ${{ github.ref_protected }}
          echo ${{ github.event.pull_request.states }}
      - run: | 
          echo "${{ tojson(github.event.pull_request) }}"

          
          
