name: CI

on: 
  push: 
    branches: [master]
#   workflow_call:
#     inputs:
#       environment:
#         required: true
#         type: string 
#     secrets: 
#       SONAR: 
#         required: true        
env:
  scripts: mongo-scripts
  test: false

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ env.test==false }}
    outputs:
      test: ${{ steps.mongo.outputs.aa }}
    env:
      test: dev
    steps:
      - uses: actions/checkout@v2
        with:
          repository: vickytestcicd/mongo
          path: mongo-scripts
      - uses: actions/checkout@v2
        with:
          path: source
      - run: |
          pwd
          ls
#       - name: check
#         id: mongo
#         run: echo "::set-output name=aa::vlaue"
#       - run: exit 1
#       - name: test
#         if: ${{ failure() }}
#         run: echo ${{ steps.mongo.outputs.aa }}

#   check:
#     runs-on: ubuntu-latest
#     needs: [test]
#     steps:
#       - run: echo 'test'
   
 
          
