name: CI

on: workflow_dispatch
  

jobs:
#   build:
#     uses: vickytestcicd/testcicd2/.github/workflows/main.yml@main
#     secrets:
#       ACCOUNT: ${{ secrets.ACCOUNT }}
#       ACCOUNT2: ${{ secrets.ACCOUNT2 }}
  test:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo 'test'
