name: CI

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'env'
        default: 'sfms-sit-1'
        type: choice
        options:
        - sfms-sit-1
        - sfms-sit-2
        - sfms-aat-1
        - sfms-aat-2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          if [github.ref_name=='release'];then
            echo '111'
          else
            echo '222'
          fi

