name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    uses: vickytestcicd/testcicd2/.github/workflows/main.yml@main
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ secrets.ACCOUNT }}
          echo ${{ secrets.ACCOUNT2 }}
