name: CI

on: 
  workflow_call:
    inputs:
      dbEnv:
        required: true
        type: string
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.dbEnv }}  
   
 
          
