name: CI

on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.test.outputs.env }}
    steps:
      - name: test
        id: test
        run: |
          if [ $GITHUB_REF_NAME == 'release' ];then
            echo "env=SIT" >> $GITHUB_OUTPUT
          else
            echo "env=FIXSIT" >> $GITHUB_OUTPUT
          fi

  test2:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: test
        id: test
        run: |
          echo ${{ needs.test.outputs.env }}

          echo ${{ vars[format('NAMESPACE_{0}', needs.test.outputs.env )]}}
