name: CI

on: 
  workflow_call:
    outputs:
      deployResulta:
        description: "the result of deployment"
        value: ${{ jobs.test.result }}
      deployResultb:
        description: "the result of deployment"
        value: ${{ jobs.test1.result }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
           exit 1
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
           exit 0
     
