name: CI

on: 
  workflow_call:
    outputs:
      deployResulta:
        description: "the result of deployment"
        value: ${{ jobs.test.outputs.aa }}
      deployResultb:
        description: "the result of deployment"
        value: ${{ jobs.test.outputs.bb }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      aa: ${{ steps.test.outputs.aa }}
      bb: ${{ steps.test.outputs.bb }}
    steps:
      - name: test
        id: test
        run: |
           echo "::set-output name=aa::valuesss"
           echo "::set-output name=bb::valuesss"
