name: CI

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: test
        id: test
        run: |
          json=$(cat test.json)

          new_json=$(echo "$json" | sed '\"consumerEnv\": \"DEV\"s/}$/,"new_field":"example"}/g')

          echo "$new_json" > test.json

          echo "Updated JSON content: $(cat test.json)"
