name: CI

on:
  push:
#   workflow_call:
#     outputs:
#       deployResulta:
#         description: "the result of deployment"
#         value: ${{ jobs.test.outputs.result }}
#       deployResultb:
#         description: "the result of deployment"
#         value: ${{ jobs.test1.outputs.result }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          exit 1
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          exit 0
  test2:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [test,test1]
    steps:
      - name: test
        id: test
        run: |
          echo ${{ needs.test.result }}
          echo ${{ needs.test1.result }}
