name: CI

on: 
  push: 
    branches: [master]
#   workflow_call:
#     inputs:
#       environment:
#         required: true
#         type: string 
#     secrets: 
#       SONAR: 
#         required: true        

  

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.mongo.outputs.aa }}
    steps:
#       - run: echo ${{ inputs.environment }}  
      - name: check
        id: mongo
        run: echo "::set-output name=aa::vlaue"
      - run: exit 1
      - name: test
        if: ${{ failure() }}
        run: echo ${{ steps.mongo.outputs.aa }}

#   check:
#     runs-on: ubuntu-latest
#     needs: [test]
#     steps:
#       - run: echo 'test'
   
 
          
