name: CI

on: 
  push: 
    branches: [master]

#     secrets: 
#       SONAR: 
#         required: true        
env:
  scripts: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
  test1:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ jobs.test.conclusion == 'failure' }}
    steps:
      - run: echo "test"


        
#       - name: check
#         id: mongo
#         run: echo "::set-output name=aa::vlaue"
#       - run: exit 1
#       - name: test
#         if: ${{ failure() }}
#         run: echo ${{ steps.mongo.outputs.aa }}

#   check:
#     runs-on: ubuntu-latest
#     needs: [test]
#     steps:
#       - run: echo 'test'
   
 
          
