name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    uses: vickytestcicd/testcicd2/.github/workflows/main.yml@main
    secrets:
      ACCOUNT: ${{ secrets.ACCOUNT }}
      ACCOUNT2: ${{ secrets.ACCOUNT2 }}
