name: CI

on: 
  workflow_call:
    outputs:
      deployResult:
        description: "the result of deployment"
        value: ${{ jobs.test.outputs.result }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      deployResult: ${{ steps.test.outputs.result }}
    steps:
      - name: test
        id: test
        run: |
           echo "::set-output name=aa::valuesss"
           echo "::set-output name=bb::valuesss"
