name: CI

on: 
  push: 
    branches: [master]
#   workflow_call:
#     inputs:
#       environment:
#         required: true
#         type: string 
#     secrets: 
#       SONAR: 
#         required: true        

  

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.mongo.outputs.aa }}
    env:
      test: dev
    steps:
      - uses: actions/checkout@v3
        with:
          repository: vickytestcicd/testcicd2
      - run: |
          ls
          cd /home/runner/work/testcicd
          ls
      - run: |
          ls
          cd /home
          ls   
      - uses: actions/checkout@v3

      - run: |
          ls
          cd /home/runner/work/testcicd
          ls
#       - name: check
#         id: mongo
#         run: echo "::set-output name=aa::vlaue"
#       - run: exit 1
#       - name: test
#         if: ${{ failure() }}
#         run: echo ${{ steps.mongo.outputs.aa }}

#   check:
#     runs-on: ubuntu-latest
#     needs: [test]
#     steps:
#       - run: echo 'test'
   
 
          
