name: CI

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'env'
        default: 'sfms-sit-1'
        type: choice
        options:
        - sfms-sit-1
        - sfms-sit-2
        - sfms-aat-1
        - sfms-aat-2
jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: SIT
    steps:
      - name: test
        id: test
        run: |
           echo '111'
  test2:
    runs-on: ubuntu-latest
    environment:
      name: FIXSIT
    steps:
      - name: test
        id: test
        run: |
           exit 1

