name: CI

on: 
  workflow_dispatch:
    inputs:
      envvalue:
        description: 'deploy env'
        required: true
        type: string
  

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      test: (a  ab 12  3a)
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          for i in ${test[*]};do echo $i;done
      - id: step1
        run: | 
          echo "::set-output name=test::$(cat test.txt))"
      - run: |
          for i in ${${{ steps.step1.outputs.test }}[*]};do echo $i;done

          
          
