name: CI

on:
  push:
#   workflow_call:
#     outputs:
#       deployResulta:
#         description: "the result of deployment"
#         value: ${{ jobs.test.outputs.result }}
#       deployResultb:
#         description: "the result of deployment"
#         value: ${{ jobs.test1.outputs.result }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          echo "test"
  test2:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: exit 1
  test3:
    runs-on: ubuntu-latest
    needs: [test2]
    steps:
      - run: echo "test3"
  test4:
    runs-on: ubuntu-latest
    needs: [test2,test3]
    if: ${{ always() && needs.test3.result != "failed" }}
    steps:
      - run: echo "test3"
    
          

#   test2:
#     needs: [test]
#     uses: vickytestcicd/mongo/.github/workflows/main.yml@main
#     with:
#       aa: ${{ needs.test.outputs.aa }}
#       bb: ${{ needs.test.outputs.bb }}
#     if: ${{ always() && ( needs.test.outputs.aa == 'true' || needs.test.outputs.bb == 'true' ) }}
#     needs: [test]
#     if: ${{ needs.test.outputs.aa == 'true' || needs.test.outputs.bb == 'true' }}

          
          
