name: CI

on: 
  push:
    branches: [main]
  

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - run: | 
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token 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" https://api.github.com/repos/vickytestcicd/testcicd/branches/main/protection
      - run: | 
          gh api -H "Accept: application/vnd.github+json"  /repos/vickytestcicd/testcicd/branches/main/protection

          
          
