name: CI

on: 
  workflow_dispatch:
    inputs:
      envvalue:
        description: 'deploy env'
        required: true
        type: string
  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: | 
          echo "test"
          echo ${{ inputs.envvalue }}

          
          
