name: CI

on:
  push:
    branches: [main]

jobs:
#   build:
#     uses: vickytestcicd/testcicd2/.github/workflows/main.yml@main
#     secrets:
#       ACCOUNT: ${{ secrets.ACCOUNT }}
#       ACCOUNT2: ${{ secrets.ACCOUNT2 }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: | 
          export test=ttt
          sed -i '3{s/$/-\$test/}' test.yaml 
          cat test.yaml
