name: CI

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          json=$(cat test.json)

          # 添加新字段
          new_json=$(echo "$json" | sed 's/}$/,"new_field":"example"}/g')

          # 将新的 JSON 字符串写入文件
          echo "$new_json" > test.json

          # 运行结果输出到控制台
          echo "Updated JSON content: $(cat test.json)"
