name: CI

on: 
  push:
    branches: [main]
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo 'test'
      - run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token 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" https://api.github.com/repos/vickytestcicd/testcicd/branches/main/protection
          
