name: CI

on: 
  push: 
    branches: [master]

#     secrets: 
#       SONAR: 
#         required: true        
env:
  scripts: false

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.mongo.outputs.aa }}
    env:
      test: dev
    steps:
      - name: hhh
        if: ${{ fromJson('["push", true]').push }}
        run: |
          echo  ${{ env.scripts }}
        
#       - name: check
#         id: mongo
#         run: echo "::set-output name=aa::vlaue"
#       - run: exit 1
#       - name: test
#         if: ${{ failure() }}
#         run: echo ${{ steps.mongo.outputs.aa }}

#   check:
#     runs-on: ubuntu-latest
#     needs: [test]
#     steps:
#       - run: echo 'test'
   
 
          
