name: CI

on: 
  workflow_call:
    outputs:
      deployResulta:
        description: "the result of deployment"
        value: ${{ jobs.test.outputs.result }}
      deployResultb:
        description: "the result of deployment"
        value: ${{ jobs.test1.outputs.result }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      aa: ${{steps.outputs.test.aa }}
    steps:
      - name: test
        id: test
        run: |
           echo "::set-output name=aa::success"
  test1:
    runs-on: ubuntu-latest
    outputs:
      bb: ${{steps.outputs.test.bb }}
    steps:
      - name: test
        id: test
        run: |
           echo "::set-output name=bb::failed"
     
